context:
  version: "9.0.0"

package:
  name: open-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/open-cli/-/open-cli-${{ version }}.tgz
  sha256: 8e3d5ef162541da90ba32392ed201628c4c65aa69bab7583a578bdc256bb35bd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - open-cli --help

about:
  license: MIT
  license_file:
    - license
    - third-party-licenses.txt
  summary: Open stuff like URLs, files, executables. Cross-platform.
  homepage: https://github.com/sindresorhus/open-cli
  repository: https://github.com/sindresorhus/open-cli

extra:
  recipe-maintainers:
    - danielnachun
